swagger: "2.0"
info:
  description: "API template"
  version: "0.0.0"
  title: "API template"
host: "mars-map-generator.herokuapp.com"
basePath: "/api/v1"
produces:
  - "application/json"
securityDefinitions:
  authorization:
    type: apiKey
    name: authorization
    in: header
paths:
  /maps:
    post:
      tags:
        - Maps
      summary: Return a randomly generated isometric map
      parameters:
        - in: body
          name: map
          description: The properties of the map.
          schema:
            type: object
            required:
              - height
              - width
            properties:
              height:
                type: integer
                example: 100
                description: Height of the map.
              width:
                type: integer
                example: 100
                description: Width of the map.
              maxDepth:
                type: integer
                example: 3
                description: Maximum number of layers.
                default: 2
              seaLevel:
                type: number
                example: 0.03
                default: 0.03
                description: \% of ice on the map.
              duneslevel:
                type: number
                example: 0.01
                default: 0.01
                description: \% of mountains on the map.
              holesLevel:
                type: number
                example: 0.01
                default: 0.01
                description: \% of holes on the map.
      responses:
        200:
          description: Return a randomly generated isometric map
        400:
          description: The required properties are not sent correctly
definitions:
  Map:
    type: array
    items:
      type: array
      items:
        type: integer
